'use client';

import React, { useState } from 'react';

export default function AiPanel({ onSuggest, suggestions }: { onSuggest: (s: any) => void; suggestions: any[] }) {
  const [text, setText] = useState('');
  const [applyTo, setApplyTo] = useState<string | ''>('');
  const [loading, setLoading] = useState(false);

  async function generateSuggestion() {
    setLoading(true);
    try {
      const payload: any = { processId: (window as any).__DEMO_PROCESS_ID || null, stepTitle: text, contextSnippets: [] };
      // If user provided applyTo step id include
      if (applyTo) payload.stepId = applyTo;

      const res = await fetch('/api/ai/suggest', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Org-Id': 'demo-org' }, body: JSON.stringify(payload) });
      const json = await res.json();
      if (res.ok) {
        const sug = {
          id: json.suggestionId,
          suggestedText: json.parsed?.suggested_text ?? json.raw ?? 'No suggestion returned',
          raci: json.parsed?.raci_recommendations ?? [],
          riskFlags: json.parsed?.risk_flags ?? [],
          applyToStepId: applyTo || null,
          notes: 'Generated by LLM',
        };
        onSuggest(sug);
      } else {
        alert('AI error: ' + (json.error ?? JSON.stringify(json)));
      }
    } catch (err) {
      console.error('AI panel error', err);
      alert('AI request failed');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="ai-panel">
      <h3>AI Assistant</h3>
      <label>Suggestion prompt (free text)</label>
      <input value={text} onChange={(e) => setText(e.target.value)} placeholder="Suggest step improvements..." />
      <label>Apply to step id (optional)</label>
      <input value={applyTo} onChange={(e) => setApplyTo(e.target.value)} placeholder="s1, s2, ..." />
      <div style={{ display: 'flex', gap: 8, marginTop: 8 }}>
        <button onClick={generateSuggestion} disabled={loading}>{loading ? 'Generating…' : 'Generate Suggestion'}</button>
      </div>

      <h4 style={{ marginTop: 12 }}>Recent suggestions</h4>
      <div>
        {suggestions.length === 0 && <div style={{ fontSize: 13, color: '#666' }}>No suggestions yet</div>}
        {suggestions.map((s: any) => (
          <div key={s.id} style={{ border: '1px solid #eee', padding: 8, marginTop: 8 }}>
            <div style={{ fontWeight: 600 }}>{s.suggestedText}</div>
            <div style={{ fontSize: 12, color: '#444' }}>{s.notes}</div>
            <div style={{ marginTop: 6 }}>
              <button
                onClick={() => {
                  alert('Applied');
                }}
              >
                Apply
              </button>{' '}
              <button
                onClick={() => {
                  alert('Reject');
                }}
              >
                Reject
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
